#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

source $PLUGIN_DIR/colors.sh

ICON_COLOR=$c_orange

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$c_white
  label.color=$c_white
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
SPACE_KEY_CODE=("18" "19" "20" "21" "23" "22" "26" "28" "25" "29")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=7
    icon.padding_right=7
    background.color=0x40ffffff
    background.corner_radius=5
    background.height=25
    label.font="sketchybar-app-font:Regular:16.0"
    label.padding_right=20
    label.y_offset=-1
    label.color=$ICON_COLOR
    script="$PLUGIN_DIR/space.sh"
    click_script="osascript -e 'tell application "\""System Events"\"" to key code ${SPACE_KEY_CODE[i]} using control down'"
    #click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left \
    --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
            script="$PLUGIN_DIR/space_app_icons.sh" \
           --subscribe chevron space_windows_change \
           --add item front_app left \
           --set front_app \
            icon.font="sketchybar-app-font:Regular:16.0" \
            icon.color=$ICON_COLOR \
            script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
            icon.color=$ICON_COLOR \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
            icon.color=$ICON_COLOR \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
            icon.color=$ICON_COLOR \
           --subscribe battery system_woke power_source_change \

# github
sketchybar --add item github.bell left \
           --set github.bell \
            associated_space=4 \
            update_freq=180 \
            icon= \
            label="Loading..." \
            script="$PLUGIN_DIR/github.sh" \
            click_script="sketchybar --set \$NAME popup.drawing=toggle"

# slack
sketchybar  --add   item slack right \
            --set   slack \
                    update_freq=180 \
                    script="$PLUGIN_DIR/slack.sh" \
                    background.padding_left=15  \
                    icon.font.size=18 \
           --subscribe slack system_woke

# gcp + k8s
sketchybar --add event k8s-changed \
           --add event gcp-changed

sketchybar --add item k8s right \
           --set k8s \
            update_freq=120 \
            icon=󱃾 \
            icon.color=$ICON_COLOR \
            script="$PLUGIN_DIR/k8s.sh" \
            click_script="$PLUGIN_DIR/k8s-click.sh" \
           --subscribe k8s k8s-changed

sketchybar --add item gcp right \
           --set gcp \
            update_freq=120 \
            icon=󱇶 \
            icon.color=$ICON_COLOR \
            script="$PLUGIN_DIR/gcp.sh" \
            click_script="$PLUGIN_DIR/gcp-click.sh" \
           --subscribe gcp gcp-changed

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
