#!/bin/bash
PLUGIN_DIR="$CONFIG_DIR/plugins"
source $PLUGIN_DIR/colors.sh
ICON_COLOR=$c_orange

##### Bar Appearance #####
sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000 notch_width=220

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$c_white
  label.color=$c_white
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# aerospace
sketchybar --add event aerospace_workspace_change

AERO_SPACES=("Q" "W" "E" "R" "T" "Y" "U" "I" "O" "P" "M")
SPACE_MONITOR=("1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2")
for i in "${!AERO_SPACES[@]}"; do
    sid=${AERO_SPACES[i]}
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        display=${SPACE_MONITOR[i]} \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        icon="$sid" \
        label.color=$ICON_COLOR \
        label.font="sketchybar-app-font:Regular:16.0" \
        label.padding_right=20 \
        label.y_offset=-1 \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

##### Adding Left Items #####
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
            script="$PLUGIN_DIR/aerospace_app_icons.sh" \
           --subscribe chevron aerospace_workspace_change \
           --add item front_app left \
           --set front_app \
            icon.font="sketchybar-app-font:Regular:16.0" \
            icon.color=$ICON_COLOR \
            script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

# github
sketchybar --add item github-pr-reviewed q \
           --set github-pr-reviewed \
            script="$PLUGIN_DIR/github/pr.sh reviewed" \
            click_script="$PLUGIN_DIR/github/pr-click.sh reviewed" \
            padding_left=3 \
            update_freq=300 \
            drawing=off \
            icon=""
sketchybar --add item github-pr-requested q \
           --set github-pr-requested \
            script="$PLUGIN_DIR/github/pr.sh requested" \
            click_script="$PLUGIN_DIR/github/pr-click.sh requested" \
            padding_left=3 \
            update_freq=300 \
            drawing=off \
            icon=""
sketchybar --add item github-pr-created q \
           --set github-pr-created \
            script="$PLUGIN_DIR/github/pr.sh created" \
            click_script="$PLUGIN_DIR/github/pr-click.sh created" \
            padding_left=3 \
            update_freq=300 \
            drawing=off \
            icon=""
sketchybar --add item github-icon q \
           --set github-icon \
           click_script="open 'https://github.com/dooris-dev'" \
            label.drawing=off \
            icon.color=$ICON_COLOR \
            icon=""
sketchybar --add bracket github github-pr-created github-pr-requested github-pr-reviewed \
           --set         github background.color=0x44ffffff \
                                background.corner_radius=4  \
                                background.height=20
##### Adding Right Items #####
sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
            icon.color=$ICON_COLOR \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
            icon.color=$ICON_COLOR \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
            icon.color=$ICON_COLOR \
           --subscribe battery system_woke power_source_change \

# slack
sketchybar  --add   item slack right \
            --set   slack \
                    update_freq=180 \
                    script="$PLUGIN_DIR/slack.sh" \
                    background.padding_left=15  \
                    icon.font.size=18 \
           --subscribe slack system_woke

# gcp + k8s
sketchybar --add event k8s-changed \
           --add event gcp-changed

sketchybar --add item k8s right \
           --set k8s \
            update_freq=120 \
            icon=󱃾 \
            icon.color=$ICON_COLOR \
            script="$PLUGIN_DIR/k8s.sh" \
            click_script="$PLUGIN_DIR/k8s-click.sh" \
           --subscribe k8s k8s-changed

sketchybar --add item gcp right \
           --set gcp \
            update_freq=120 \
            icon=󱇶 \
            icon.color=$ICON_COLOR \
            script="$PLUGIN_DIR/gcp.sh" \
            click_script="$PLUGIN_DIR/gcp-click.sh" \
           --subscribe gcp gcp-changed

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
