[window]
option_as_alt = "OnlyLeft"
decorations = "Buttonless"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold   = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
